# Generated by Django 4.2.5 on 2023-10-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_curso_tarea_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='curso',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inglés'), (2, 'Francés'), (3, 'Español')]),
        ),
    ]
